name: Pull And Push To Aliyun
on:
  workflow_dispatch: # 保留：支持网页手动执行
  push:
    paths:
      - 'images.txt'  # images.txt文件变更自动触发
env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check docker version
        run: docker --version
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 登录阿里云ACR镜像仓库
        run: |
          echo "正在登录阿里云容器镜像仓库"
          docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
          echo "✅ 阿里云仓库登录完成"

      - name: 读取images.txt循环同步镜像
        run: |
          # 读取images.txt，循环每一行
          while IFS= read -r SOURCE_IMG; do
            # 跳过空行
            if [[ -z "$SOURCE_IMG" ]]; then
              continue
            fi
            echo "====================================="
            echo "🔄 当前处理镜像: $SOURCE_IMG"
            
            # 把 / 和 : 替换成下划线，作为阿里云镜像名称
            IMG_NAME=$(echo "$SOURCE_IMG" | sed 's/\//_/g')
            TARGET_IMG="${ALIYUN_REGISTRY}/${ALIYUN_NAME_SPACE}/${IMG_NAME}"
            
            echo "开始拉取镜像 $SOURCE_IMG"
            docker pull "$SOURCE_IMG"
            echo "✅ $SOURCE_IMG 拉取成功"

            echo "打标签：$SOURCE_IMG -> $TARGET_IMG"
            docker tag "$SOURCE_IMG" "$TARGET_IMG"

            echo "推送到阿里云ACR $TARGET_IMG"
            docker push "$TARGET_IMG"
            echo "✅ $SOURCE_IMG 推送阿里云成功"

            echo "清理本地镜像 $SOURCE_IMG"
            docker rmi "$SOURCE_IMG" || true
            docker rmi "$TARGET_IMG" || true
            echo "✅ 本地镜像清理完毕"
          done < images.txt
